BASE_URL = "https://understat.com/"
LEAGUE_URL = "https://understat.com/league/{}/{}"
PLAYER_URL = "https://understat.com/player/{}"
TEAM_URL = "https://understat.com/team/{}/{}"
MATCH_URL = "https://understat.com/match/{}/"
PATTERN = r"{}\s+=\s+JSON.parse\(\'(.*?)\'\)"
